# Generated by Django 4.1.1 on 2022-09-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre de la posicion')),
                ('description', models.TextField(max_length=25, verbose_name='Descripcion de la posicion')),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'Posicion',
                'ordering': ['id'],
            },
        ),
    ]
