# Generated by Django 4.1.1 on 2022-09-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('Surname', models.TextField(max_length=25, verbose_name='Apellido')),
                ('Date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Nationality', models.CharField(max_length=25, verbose_name='Nacionalidad')),
                ('Role', models.CharField(max_length=25, verbose_name='Rol (técnico | asistente | médico | preparador)')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'Tecnico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre de equipo')),
                ('flag', models.ImageField(blank=True, upload_to='media')),
                ('Shield', models.ImageField(blank=True, upload_to='media')),
                ('Technical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technical')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('Surname', models.TextField(max_length=25, verbose_name='Apellido')),
                ('Photo', models.ImageField(blank=True, upload_to='media')),
                ('Date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Number', models.IntegerField(verbose_name='Numero de  camisa')),
                ('Headline', models.CharField(max_length=25, verbose_name='Es titular')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugador',
                'ordering': ['id'],
            },
        ),
    ]
